name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
      - closed
      - assigned
env:
  PROJECT_NAME: Qiita
jobs:
  issue_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add backlog label
        if: "github.event.action == 'opened'"
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "backlog"
          remove-labels: "inprogress, close"
          repo-token: ${{ secrets.PAT }}
      - name: Add inprogress label
        if: "github.event.action == 'assigned' || github.event.action == 'reopened'"
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "inprogress"
          remove-labels: "backlog, close"
          repo-token: ${{ secrets.PAT }}
      - name: Add close label
        if: "github.event.action == 'closed'"
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "close"
          remove-labels: "inprogress, backlog"
          repo-token: ${{ secrets.PAT }}

  assign_issue_to_project:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        if: "github.event.action == 'opened'"
        with:
          PROJECT: ${{env.PROJECT_NAME}}
          COLUMN: Backlog

  move_assigned_card:
    runs-on: ubuntu-latest
    name: Move assigned card
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: "github.event.action == 'assigned'"
        with:
          project: ${{env.PROJECT_NAME}}
          column: In Progress
          repo-token: ${{ secrets.PAT }}
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: "github.event.action == 'reopened'"
        with:
          project: ${{env.PROJECT_NAME}}
          column: In Progress
          repo-token: ${{ secrets.PAT }}